// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxgDUkxfc9wml1I_kA5DUMOaOe-AlyB28',
    appId: '1:590091208411:web:ad8fb4632175ee5d56aefe',
    messagingSenderId: '590091208411',
    projectId: 'quickfill-b1d71',
    authDomain: 'quickfill-b1d71.firebaseapp.com',
    storageBucket: 'quickfill-b1d71.appspot.com',
    measurementId: 'G-X4GKHX00GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX3dVx5A5TEV-b9CbWAsih_-RBsBuwQSM',
    appId: '1:590091208411:android:7c733d357f14ac5156aefe',
    messagingSenderId: '590091208411',
    projectId: 'quickfill-b1d71',
    storageBucket: 'quickfill-b1d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1ZjalxMjoowSerrKkkEkyNcNJglfpPo',
    appId: '1:590091208411:ios:cba25fbc8023a5bd56aefe',
    messagingSenderId: '590091208411',
    projectId: 'quickfill-b1d71',
    storageBucket: 'quickfill-b1d71.appspot.com',
    androidClientId: '590091208411-4dnaicvvncr8t35kiu57n4nftjqbkmg5.apps.googleusercontent.com',
    iosClientId: '590091208411-eil80ghg5haqq6khbjuga35jvvs83iec.apps.googleusercontent.com',
    iosBundleId: 'com.calletic.quickfillcustomer.quickfillcustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq1ZjalxMjoowSerrKkkEkyNcNJglfpPo',
    appId: '1:590091208411:ios:972aac74396be64956aefe',
    messagingSenderId: '590091208411',
    projectId: 'quickfill-b1d71',
    storageBucket: 'quickfill-b1d71.appspot.com',
    androidClientId: '590091208411-4dnaicvvncr8t35kiu57n4nftjqbkmg5.apps.googleusercontent.com',
    iosClientId: '590091208411-vgfgsri9ls6gra565b6r87rhfor5q5pt.apps.googleusercontent.com',
    iosBundleId: 'com.calletic.quickfillcustomer.quickfillcustomer.RunnerTests',
  );
}
